name: michicolle
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  permission_handler: ^11.3.1
  bordered_text: ^2.0.0
  location: ^7.0.1
  flutter_map_animations: ^0.8.0
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_expandable_fab: ^2.3.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: keifont
      fonts:
        - asset: lib/assets/fonts/keifont/keifont.ttf
  assets:
    - .env.development
    - .env.production
